# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ad371b43fbc0eee197c9f3a8368e63344ff9df4ddd1d89212f94b75e8d48614f6d514d2919c1fe7e4b8c0d71f274e97a039847543c59fbf5443ef8373e202af

test:
  secret_key_base: 2dd8d9be5b634ece1535eeb157a044cbcc182c5d9079845ebbe5d65847986cb18b001f1c9165de1e667156867ff5810e47519e245a98f6c9118efd51e930a47e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
